<html>
<head>
<meta name="viewport" content="width=device-width" />
<?php
### generate input screen and insert new accession data ###
include '/var/www/bcm/credentials.php';

try {
	$db = new PDO('mysql:host=localhost;dbname=bcm;charset=utf8mb4',$user,$password);
} catch(PDOException $ex) {
	echo 'An Error occurred connecting to BCM'.chr(10); ## User Friendly Message
	echo $ex-getMessage().chr(10); # Explicit Error Message
}

$sql = 'select max(codeno) from gh_inv where codeno<100000000';
$sth = $db->prepare($sql);
$sth->execute();
$codeno = $sth->fetchColumn();
$codeno++;

echo '</head><body>';
echo '<h3>UConn EEB Greenhouse - Wishlist Entry</h3><hr>';


echo '<h1>New Wishlist Entry</h1>';

echo '<table><tr><form action="http://florawww.eeb.uconn.edu/bcm/insert_new_acc.php" method="post"></tr>';
echo '<tr><td>Codeno:</td><td><input name="codeno" value='.$codeno.'><i>{next available autogenerated, change as needed}</i></td></tr>';
echo '<tr><td>Genus:</td><td><input name="genus" value=""><i>{must be valid genus name ONLY}</i></td></tr>';
echo '<tr><td>Species:</td><td><input name="species" value=""><i>{can include varietal names}</i></td></tr>';
echo '<tr><td>Source:</td><td><input name="source" value=""><i>{proposed source}</i></td></tr>';
echo '<input name="location" type="hidden" value="0">';
echo '<input name="quant" type="hidden" value="0">';
echo '<tr><td>Project:</td><td><input name="projnum" value="WISHLIST"></td></tr>';
echo '<tr><td></td><td><input type="submit" value="Create Accession"></td></tr>';
echo '</form></table>';

$db = null;
?> 
